services:
  findrr:
    image: newandreas/findrr:latest
    container_name: findrr
    restart: unless-stopped
    ports:
      - "6580:6580"
    volumes:
      - ./config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - PYTHONUNBUFFERED=1